### ISSUE TITLE
snort install

### ISSUE THREAD

**Issue by zhuyihenzheng** [zhuyihenzheng/0118Test#6]

**Comment by oucyou** [comment]
yum install gcc-c++
yum install daq-devel.x86_64 
libdnet/include/dnet/Makefile.in 
sctp.h add
   109  yum install hwloc-devel.x86_64
  111  yum install luajit-devel.x86_64 
  113  yum install openssl-devel.x86_64 
  118  yum install libdnet-devel.x86_64 
  125  yum install pcre2-devel.x86_64 
  126  yum install pkgconfig.i686 
  127  yum install zlib-ada-devel.x86_64 
  132  yum install libdnet-python.x86_64 
  151  yum install libnfnetlink-devel.x86_64
  152  yum install libnetfilter_queue 
  154  yum install libnetfilter_queue-devel.x86_64 
  160  yum install hwloc-gui.x86_64 
  161  yum install hwloc-plugins.x86_64 
  180  yum install hwloc.x86_64

**Comment by oucyou** [comment]
[cry.pcap.zip](https://github.com/oucyou/0118Test/files/1863005/cry.pcap.zip)
