### ISSUE TITLE
lzrw1/kh

### ISSUE THREAD

**Issue by zhuyihenzheng** [zhuyihenzheng/0118Test#9]
import sys, os
from ctypes import *
from pdb import set_trace

def decompress(data):
    data_len = len(data)
    data = create_string_buffer(data)
    try:
        lznt1 = cdll.LoadLibrary(os.path.abspath('lzrw1kh.so'))
        unpacked_data = create_string_buffer(data_len*100)
        unpacked_len = lznt1.lzrw1kh_Decompression(data,  unpacked_data, c_int(data_len))
        if unpacked_len == 0:
            print 'Error: Could not decompress data'
            return False
        with open(os.path.abspath('out2.txt') ,'wb') as out2:
            out2.write(unpacked_data.value)
            out2.close()
        print unpacked_data.value
        print unpacked_len
        return unpacked_data
    except Exception,e:
        print '%s'%e

def compress(data):
    data_len = len(data)
    data = create_string_buffer(data)
    try:
        lznt1 = cdll.LoadLibrary(os.path.abspath('lzrw1kh.so'))
        packed_data = create_string_buffer(len(data)*2)
        packed_len = lznt1.lzrw1kh_Compression(data,  packed_data, c_int(data_len))
        packed_data = "".join(packed_data[:packed_len])
        with open(os.path.abspath('out.txt') ,'wb') as out:
            out.write(packed_data)
            out.close()
        print packed_len
        print packed_data
        if packed_len == 0:
            print 'Error: Could not decompress data'
            return False
        return packed_data
    except Exception,e:
        print '%s'%e

if __name__ == "__main__":
    with open(sys.argv[1]) as indata:
        data = indata.read()
        indata.close()
    if sys.argv[2] == "d":
        print "testd"
        unpacked = decompress(data)
    else:
        print "testc"
        unpacked = compress(data)

**Comment by oucyou** [comment]
[lzrwandlznt.tar.gz](https://github.com/oucyou/0118Test/files/2087980/lzrwandlznt.tar.gz)

**Comment by oucyou** [comment]
import itertools
import base64
import re,sys
n = 0
m = 0
list1=[]
list2=[]
list3=[]
list4=[]
for i in itertools.permutations('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', 4):
    data = ''.join(i)
    #print(data)
    try:
        endata = base64.b64decode(data)
        if re.match(r"[0-9a-zA-Z]{3}", endata, re.M|re.I) :
            if not i[0] in list1:
                list1.append(i[0])
            if not i[1] in list2:
                list2.append(i[1])
            if not i[2] in list3:
                list3.append(i[2])
            if not i[3] in list4:
                list4.append(i[3])
            #print "test:" + data
            n = n + 1
        else:
            m = m + 1
    except Exception, e:
         
        #print e
        #sys.exit(1)
        m = m + 1
print n
print m
print list1
print list2
print list3
print list4
